### ISSUE TITLE
Runtime error response

### ISSUE THREAD

**Issue by ahmetanildindar** [komoot/staticmap#19]
Hi there,
I've been using staticmap for long time in my programs. Your work is very much appreciated. 

This morning, I've started having the following response and failed using staticmap. 

`
Raise RuntimeError("could not download {} tiles: {}".format(len(tiles), tiles))
RuntimeError: could not download 4 tiles: [(16, 10, 'http://a.tile.osm.org/5/16/10.png'), (16, 11, 'http://a.tile.osm.org/5/16/11.png'), (17, 10, 'http://a.tile.osm.org/5/17/10.png'), (17, 11, 'http://a.tile.osm.org/5/17/11.png')]
`

The screenshot for what I see is below. 
![image](https://user-images.githubusercontent.com/3111609/58750854-cddd2700-849f-11e9-86d8-51ecab01e298.png)

I wonder whether this is a critical issue or not?

Do you have any suggestion?

**Comment by ahmetanildindar** [comment]
Dear all,
The issue was solved by uninstalling and then re-installing static map :)))

Static map is a really useful module I used in my studies.

Regards from Istanbul.

AAD

**Comment by brauchle** [comment]
FYI: had the same issue, for me the problem was that the official OSM tile server blocked requests that have no user agent header.

So for me adding headers={"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"} fixed the issue.

**Comment by kambrium** [comment]
Thanks @brauchle! This is really helpful.
